main/urls.py
from django.urls import path
from . import views
from .views import ProjetListView, \
    ProjetDetailView, \
    ProjetCreateView, \
    ProjetUpdateView, \
    ProjetDeleteView, \
    UserProjetListView

urlpatterns = [
    path('like/<int:pk>/<int:pkcom>/', views.like_comment, name='main-like'),
    path('', views.projetFinance, name='main-home'),
    path('privacy/', views.privacy, name='main-privacy'),
    path('search/', views.recherche, name='main-search'),
    path('projets', ProjetListView.as_view(), name='main-projets'),
    path('projet/<str:username>', UserProjetListView.as_view(), name='user-projets'),
    path('projet/<int:pk>/', ProjetDetailView.as_view(), name='projet-detail'),
    path('projet/new/', ProjetCreateView.as_view(), name='projet-create'),
    path('projet/<int:pk>/update/', ProjetUpdateView.as_view(), name='projet-update'),
    path('projet/<int:pk>/delete/', ProjetDeleteView.as_view(), name='projet-delete'),
    path('projet/<int:pk>/comment/', views.add_comment_to_projet, name='add_comment_to_projet'),
    path('projet/<int:pk>/financer/', views.financer_projet, name='financer_projet'),
    path('projet/<int:pk>/evaluer/', views.evaluer_projet, name='evaluer_projet'),
    path('about/', views.about, name='main-about'),
    path('contact/', views.contact, name='main-contact'),
]

mopga/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", user_views.register, name="register"),
    path("profile/", user_views.profile, name="profile"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
    path('', include('main.urls')),
    path('rss/', include('rss.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rss/urls.py
from django.urls import path
from .rss import LastestProjectsFeed


urlpatterns = [
    path('', LastestProjectsFeed(), name='rss'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from PIL import Image
from django.db.models import Sum, Avg


class Projet(models.Model):
    intitule = models.CharField(max_length=200)
    description = models.TextField()
    # le monatant souhaité pour le projet
    montant_souhaite = models.DecimalField(default=0.00, max_digits=10, decimal_places=2, blank=True)
    #image = models.ImageField(default="projet-default.jpg", upload_to="projects_pics//%d-%m-%Y-%H-%M-%S")
    image = models.ImageField(default="projet-default.jpg", upload_to="projects_pics/")
    auteur = models.ForeignKey(User, on_delete=models.CASCADE)
    # est_financé = true si le projet atteint le montant souhaité
    est_finance = models.BooleanField(default=False)
    date_finance = models.DateTimeField(default=None, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.intitule

    def get_absolute_url(self):
        return reverse('projet-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        """
        redéfinition de la méthode pour effectuer des opérations
        juste avant l'enregistrement du Projet
        """
        super().save(*args, **kwargs)

        """
        ici nous allons redimensionner notre Image
        pour pouvoir stocker des fichiers de petite taille
        """
        img = Image.open(self.image.path)

        output_size = (200, 200)
        img.thumbnail(output_size)
        img.save(self.image.path)


"""
Commentaire: permet à un user de rédiger un commentaire pour un projet
"""


class Commentaire(models.Model):
    contenu = models.TextField(max_length=1500)
    auteur = models.ForeignKey(User, on_delete=models.CASCADE)
    projet = models.ForeignKey(Projet, on_delete=models.CASCADE)
    reactions = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.contenu

"""
Financer: permet à un user de financer un projet
"""


class Financer(models.Model):
    financeur = models.ForeignKey(User, on_delete=models.CASCADE)
    projet = models.ForeignKey(Projet, on_delete=models.CASCADE)
    montant = models.DecimalField(default=0.00, max_digits=10, decimal_places=2, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.financeur.username


"""
Evaluer: permet de donner une evaluation à un projet par un user
Si le user est 'expert’ il pourra évaluer le projet avec une note
"""

class Evaluer(models.Model):
    evaluateur = models.ForeignKey(User, on_delete=models.CASCADE)
    projet = models.ForeignKey(Projet, on_delete=models.CASCADE)
    note_projet = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(10)])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.evaluateur.username


"""
Like permet de sauvegarder les réactions des utilisateurs pour les commentaires
"""
class Like(models.Model):
    like_authenticate_user = models.ForeignKey(User, on_delete=models.CASCADE)
    evaluation = models.ForeignKey(Commentaire, on_delete=models.CASCADE)
    type = models.PositiveIntegerField(default=0)
    date_like = models.DateTimeField(auto_now_add=True, blank=True)


class ProjetManager(models.Manager):

    """
    Vérifier si un projet est financé
    """
    def est_finance(self):
        total = Financer.objects.annotate(total=Sum('montant')).filter(pk=self.pk)
        projet = Projet.objects.all().filter(pk=self.pk).first()

        montant_requis = projet.montant_souhaite

        return (total >= montant_requis)


    """
    Calculer la note moyenne d'un projet
    """

    def note_moyenne(self):
        moyenne = Evaluer.objects.aggregate(average_rating=Avg('note_projet')).filter(pk=self.pk)

        return moyenne

    """
    Calculer les 'Points gagnés' pour un utilisateur
    """
    def points_gagnes(self):

        return 0

main/forms.py
from django import forms
from .models import Commentaire, Financer, Evaluer

"""
Form d'ajout d'un commentaire
"""
class CommentForm(forms.ModelForm):

    class Meta:
        model = Commentaire
        fields = ['contenu']


"""
Form d'ajout d'un montant pour financer un projet
"""
class FinancerForm(forms.ModelForm):

    class Meta:
        model = Financer
        fields = ['montant']


"""
Form d'ajout d'une note pour evaluer un projet
"""
class EvaluerForm(forms.ModelForm):

    class Meta:
        model = Evaluer
        fields = ['note_projet']


"""
Contact Form
"""
class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

main/views.py
from django.http import HttpResponse
from main.functions import *
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib import messages
from .forms import CommentForm, FinancerForm, EvaluerForm, ContactForm
from .models import Projet, Commentaire, Like, Financer
from django.contrib.auth.decorators import login_required
import re
from django.db.models import Q

"""
home: afficher les projets
"""
def home(request):
    context = {
        'title': 'Home Page',
        'content_title': 'Projets publiés',
        'projets': Projet.objects.all()
    }
    return render(request, 'main/home.html', context)


"""
about: la page Qui sommes-nous
"""
def about(request):
    context = {
        'title': 'About'
    }
    return render(request, 'main/about.html', context)


"""
La page contact --> Envoyer un mail
"""
def contact(request):

    context = {
        'title': 'Contactez-nous'
    }

    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['msalimyoussef@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            messages.success(request, "Votre mail est bien envoyé, Merci.")
            return redirect('main-contact')
    return render(request, "main/contact.html", {'form': form})


"""
Aficher le dernier projet financé
"""
def projetFinance(request):

    projet = Projet.objects.filter(est_finance=True).order_by('-date_finance').last()

    context = {
        'commentaires': Commentaire.objects.all().filter(projet=projet),
        'projet': projet
        #'note_moyenne': note_moyenne(projet.pk)
    }

    return render(request, 'main/home.html', context)


def privacy(request):
    context = {
        'title': 'Mentions légales'
    }
    return render(request, 'main/privacy_policy.html', context)


"""
Afficher les projets par date de création et avec une paggination en 3
"""
class ProjetListView(ListView):
    model = Projet
    template_name = 'main/projet/projets.html'
    context_object_name = 'projets'
    ordering = ['-created_at']
    paginate_by = 3


"""
Afficher les projets d'un utilisateur par date de création et avec une paggination en 3
"""
class UserProjetListView(ListView):
    model = Projet
    template_name = 'main/projet/user_projets.html'
    context_object_name = 'projets'
    paginate_by = 3

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Projet.objects.filter(auteur=user).order_by('-created_at')


"""
Afficher les details d'un projet et aussi ces commentaires
"""
class ProjetDetailView(DetailView):
    model = Projet
    template_name = 'main/projet/projet_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        commentaires = Commentaire.objects.all().filter(projet=self.kwargs['pk'])
        projet = get_object_or_404(Projet, pk=self.kwargs['pk'])

        context['commentaires'] = commentaires
        context['note_moyenne'] = note_moyenne(self.kwargs['pk'])

        projet = get_object_or_404(Projet, pk=self.kwargs['pk'])

        if self.request.method == "POST":
            form = CommentForm(self.request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.projet = projet
                comment.auteur = self.request.user
                comment.save()
                return redirect('projet-detail', pk=projet.pk)
        else:
            form = CommentForm()

        context['form'] = form

        return context


"""
Créer un nouveau projet
"""
class ProjetCreateView(LoginRequiredMixin, CreateView):
    model = Projet
    template_name = 'main/projet/projet_form.html'

    fields = ['intitule', 'description', 'montant_souhaite', 'image']

    def form_valid(self, form):
        form.instance.auteur = self.request.user
        return super().form_valid(form)


"""
Modifier un projet
"""
class ProjetUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Projet
    template_name = 'main/projet/projet_form.html'

    fields = ['intitule', 'description', 'montant_souhaite', 'image']

    def form_valid(self, form):
        form.instance.auteur = self.request.user
        return super().form_valid(form)

    def test_func(self):
        projet = self.get_object()
        if self.request.user == projet.auteur:
            return True
        return False

"""
Supprimer un projet
"""
class ProjetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Projet
    template_name = 'main/projet/projet_confirm_delete.html'

    success_url = '/'

    def test_func(self):
        projet = self.get_object()
        if self.request.user == projet.auteur:
            return True
        return False

"""
Ajouter un commentaire à un projet
"""
@login_required
def add_comment_to_projet(request, pk):
    projet = get_object_or_404(Projet, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.projet = projet
            comment.auteur = request.user
            comment.save()
            return redirect('projet-detail', pk=projet.pk)
    else:
        form = CommentForm()
    return render(request, 'main/projet/add_comment_to_projet.html', {'form': form})

"""
Réactions des utilisateurs avec les commentaires
"""
@login_required
def like_comment(request, pk, pkcom):
    commentaire = Commentaire.objects.all().filter(pk=pkcom).first()
    user = User.objects.all().filter(pk=request.user.pk).first()
    reaction_commentaire_fromdb = Like.objects.all().filter(like_authenticate_user=user, evaluation=commentaire).first()
    if reaction_commentaire_fromdb is None:
        reaction_commentaire = Like()
        reaction_commentaire.evaluation = commentaire
        reaction_commentaire.like_authenticate_user = user
        reaction_commentaire.type = 1
        Commentaire.objects.all().filter(pk=pkcom).update(reactions=commentaire.reactions + 1)
        reaction_commentaire.save()

    else:
        reaction_commentaire_fromdb.delete()
    return redirect('projet-detail', pk=pk)


"""
Financer un projet: permet d'ajouter un montant afin de participer au financement d'un projet
"""
@login_required
def financer_projet(request, pk):
    projet = get_object_or_404(Projet, pk=pk)
    if request.method == "POST":
        form = FinancerForm(request.POST)
        if form.is_valid():
            finance = form.save(commit=False)
            finance.projet = projet
            finance.financeur = request.user
            finance.save()

            # verifier si le projet est financé
            # Probleme combaraison entre decimal et QuerySet
            #est_finance(pk)

            return redirect('projet-detail', pk=projet.pk)
    else:
        form = FinancerForm()
    return render(request, 'main/projet/financer_projet.html', {'form': form})


"""
Permet l'evaluation d'un projet via l'ajout d'une note
"""
@login_required
def evaluer_projet(request, pk):
    projet = get_object_or_404(Projet, pk=pk)
    if request.method == "POST":
        form = EvaluerForm(request.POST)
        if form.is_valid():
            evaluation = form.save(commit=False)
            evaluation.projet = projet
            evaluation.evaluateur = request.user
            evaluation.save()
            return redirect('projet-detail', pk=projet.pk)
    else:
        form = EvaluerForm()
    return render(request, 'main/projet/evaluer_projet.html', {'form': form})


"""
Page Recherche
"""
def recherche(request):
    projets = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']

        entry_query = get_query(query_string, ['intitule', 'description'])

        projets = Projet.objects.filter(entry_query)

    return render(request, 'main/recherche.html', {'projets': projets})



def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    ''' Splits the query string in invidual keywords, getting rid of unecessary spaces
        and grouping quoted words together.
        Example:

        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']

    '''
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]

def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
        aims to search keywords within a model by testing the given search fields.

    '''
    query = None # Query to search for every search term
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query

main/templates/main/projet/add_comment_to_projet.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Ajouter un commentaire</h1>
    </div>

    <div class="row">
        <div class="col-xl-8 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">

                                    </div>
                                </div>
                                <div class="col">
                                    <form method="POST" class="post-form">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <button type="submit" class="btn btn-outline-info">Envoyer</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/projet/evaluer_projet.html
{% extends "main/base.html" %}
{% block content %}

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Donner une note pour le projet</h1>
    </div>

    <div class="row">
        <div class="col-xl-8 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">

                                    </div>
                                </div>
                                <div class="col">
                                    <form method="POST" class="post-form">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <button type="submit" class="btn btn-outline-info">valider</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/projet/financer_projet.html
{% extends "main/base.html" %}
{% block content %}

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Participer au financement du projet</h1>
    </div>

    <div class="row">
        <div class="col-xl-8 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">

                                    </div>
                                </div>
                                <div class="col">
                                    <form method="POST" class="post-form">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <button type="submit" class="btn btn-outline-info">valider</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/main/projet/projet_confirm_delete.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Supprimer Projet</legend>
                <h2>Voulez-vous vraiment supprimer le projet "{{ object.intitule }}"?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger">Oui, Supprimer</button>
                <a class="btn btn-outline-secondary" href="{% url 'projet-detail' object.id %}">Annuler</a>
            </div>
        </form>
    </div>
{% endblock content %}

main/templates/main/projet/projet_detail.html
{% extends "main/base.html" %}
{% block content %}

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Projet: {{ object.intitule }}</h1>
    </div>

    {% if object.auteur == user %}
        <div>
            <a href="{% url 'projet-update' object.id %}"
               class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-2">
                <i class="fas fa-edit fa-sm text-white-50 mr-1"></i>Modifier</a>
            <a href="{% url 'projet-delete' object.id %}"
               class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-2">
                <i class="fas fa-trash fa-sm text-white-50 mr-1"></i>Supprimer</a>
        </div>
    {% endif %}

    <!-- Content Row -->
    <div class="row">

        {% if projet %}
            <div class="col-lg-8 mb-4">

                <div class=" card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">{{ object.intitule }}</h6>
                    </div>
                    <div class="card-body">
                        <div class="text-center">
                            <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;"
                                 src="{{ object.image.url }}" alt="">
                        </div>
                        <p>
                            {{ object.description }}
                        </p>
                        <hr>
                        <p class="mt-3" style="color: #36b9cc;">Montant requis: {{ object.montant_souhaite }} euros</p>
                        <p class="mt-3" style="color: #36b9cc;">Note moyenne: {{ note_moyenne.moyenne }}</p>
                        <hr>
                        <small class="text-muted">
                            Par <a href="{% url 'user-projets' object.auteur.username %}">{{ object.auteur }}</a>
                            - {{ object.created_at| date:"F D, Y - G:i" }}
                        </small>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>


    <a href="{% url 'financer_projet' pk=projet.pk %}"
       class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-2">
        <i class="fas fa-money-bill fa-sm text-white-50 mr-1"></i>Financer</a>

    <a href="{% url 'evaluer_projet' pk=projet.pk %}"
       class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-2 {% if object.auteur == user or not user.profile.is_expert %} disabled {% endif %}">
        <i class="fas fa-check-circle fa-sm text-white-50 mr-1"></i>Noter le projet</a>

    <a href="{% url 'add_comment_to_projet' pk=projet.pk %}"
       class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-2">
        <i class="fas fa-pen fa-sm text-white-50 mr-1"></i>Ajouter un
        commentaire</a>

    {% for commentaire in commentaires %}
        <div class="row">
            <div class="col-xl-8 col-md-6 mb-4">
                <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                    {{ commentaire.auteur.username }} - {{ commentaire.created_at }}
                                </div>
                                <div class="row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
                                            <img class="img-profile rounded-circle"
                                                 src="{{ commentaire.auteur.profile.image.url }}">
                                        </div>
                                    </div>
                                    <div class="col">
                                        <p>{{ commentaire.contenu }}</p>
                                    </div>
                                </div>
                            </div>


                            <div class="col-auto">
                                <a class="float-right ml-2" href="{% url 'main-like' object.id commentaire.id %}">
                                    <i class="fas fa-thumbs-up fa-2x" {% if commentaire.like_set.count > 0 %}style="color: #36b9cc;"{% else %} style="color: #858796;" {% endif %}></i>
                                </a>
                                <div class="text-xs font-weight-bold text-info text-uppercase mt-1">
                                    {% if commentaire.like_set.count > 0 %}
                                        {{ commentaire.like_set.count }}
                                    {% endif %}
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    {% block javascript %}

    {% endblock %}

{% endblock content %}

main/templates/main/projet/projet_form.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Projet</h1>
    </div>

    <div class="row">
        <div class="col-xl-8 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                            </div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">

                                    </div>
                                </div>
                                <div class="col">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <fieldset class="form-group">
                                            <legend class="border-bottom mb-4"></legend>
                                            {{ form|crispy }}
                                        </fieldset>
                                        <div class="form-group">
                                            <button class="btn btn-outline-info">valider</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}